version: "3.8"
services: 
  api-gateway: 
    build: ./api-gateway
    ports: 
      - "8080:8080"
    depends_on:
      - timescaledb
  
  data-ingestion: 
    build: ./data-ingestion
    depends_on:
      - api-gateway
      - timescaledb

  timescaledb: 
    image: timescale/timescaledb:latest-pg16
    ports: 
      - "5432:5432" 
    environment:
      - POSTGRES_PASSWORD=teslagivemejob
    volumes: 
      - timescaledb_data:/var/lib/postgresql/data 

  monitoring: 
    build: ./monitoring
    depends_on:
      - data-ingestion
      - timescaledb

  simulator: 
    build: ./simulator
    depends_on: 
      - api-gateway
    environment:
      - INSTANCE_COUNT=5

volumes:
  timescaledb_data:

  