version: "3.8"
services: 
  gateway: 
    build: 
      context: .
      dockerfile: gateway/Dockerfile
    ports: 
      - "8080:8080"
    depends_on:
      - timescaledb
      - rabbitmq
  
  rabbitmq: 
    image: rabbitmq:3-alpine
    ports: 
      - "5672:5672"  # AMQP port
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  ingestion: 
    build: 
      context: .
      dockerfile: ingestion/Dockerfile
    depends_on:
      - rabbitmq
      - timescaledb

  timescaledb: 
    image: timescale/timescaledb:latest-pg16
    ports: 
      - "5432:5432" 
    environment:
      - POSTGRES_PASSWORD=dbpassword
    volumes: 
      - timescaledb_data:/var/lib/postgresql/data 
    depends_on:
      - rabbitmq

  monitoring: 
    build: 
      context: .
      dockerfile: monitoring/Dockerfile
    depends_on:
      - gateway
      - ingestion
      - timescaledb
      - rabbitmq

  simulator: 
    build: ./simulator
    depends_on: 
      - gateway
      - ingestion
      - timescaledb
      - rabbitmq
      - monitoring
    environment:
      - INSTANCE_COUNT=5

volumes:
  timescaledb_data:

  